[export.rename]
"Buffer" = "uint8_t"
"CommandEncoder" = "uint8_t"
"TextureView" = "uint8_t"
"Texture" = "uint8_t"
"RenderPass" = "uint8_t"
"Surface" = "uint8_t"
"Device" = "uint8_t"
"Gpu" = "uint8_t"
"FfiStr" = "uint8_t"