[export.rename]
"Buffer" = "uint8_t"
"CommandEncoder" = "uint8_t"
"TextureView" = "uint8_t"
"Texture" = "uint8_t"
"RenderPass" = "uint8_t"
"Device" = "uint8_t"
"Gpu" = "uint8_t"
"FfiStr" = "char*"
"WmRenderer" = "uint8_t"
"StagingBelt" = "uint8_t"
"BufferView" = "uint8_t"
"QueueWriteBufferView" = "uint8_t"
"SurfaceTexture" = "uint8_t"
"Sampler" = "uint8_t"