version: "0.0.1"
support: wgsl
resources:
  mvp_mat4:
    type: mat4
    mult: [wm_mat4_projection]
  rename:
    type: texture_2d
pipelines:
  terrain:
    geometry: wm_geo_terrain
    depth: wm_framebuffer_depth
    output: [wm_framebuffer_texture]
    blending: premultiplied_alpha_blending
    clear: true
    push_constants:
      0: wm_pc_chunk_position
      12: wm_pc_framebuffer_size
    uniforms:
      0: mvp_mat4
      1: wm_texture_atlas_blocks
      2: wm_ssbo_chunk_vertices
      3: wm_ssbo_chunk_indices
      4: wm_tex_electrum_lightmap
  entity:
    geometry: wm_geo_entities
    depth: wm_framebuffer_depth
    output: [wm_framebuffer_texture]
    push_constants:
      0: wm_pc_parts_per_entity
    uniforms:
      0: mvp_mat4
      1: wm_ssbo_entity_part_transforms
      2: wm_texture_entities
      3: wm_ssbo_entity_part_overlays
  electrum_gui:
    geometry: wm_geo_electrum_gui
    output: [wm_framebuffer_texture]
#    blending: premultiplied_alpha_blending
    uniforms:
      0: wm_electrum_mat4
      1: wm_electrum_gl_texture