version: "0.0.1"
support: wgsl
resources:
  mvp_mat4:
    type: mat4
    mult: [wm_mat4_projection]
  rename:
    type: texture_2d
pipelines:
  terrain:
    geometry: wm_geo_terrain
    depth: wm_framebuffer_depth
    output: [wm_framebuffer_texture]
    push_constants:
      0: wm_pc_chunk_position
    uniforms:
      0: mvp_mat4
      1: wm_texture_atlas_blocks
      2: rename
  electrum_gui:
    geometry: wm_geo_electrum_gui
    output: [wm_framebuffer_texture]
#    depth: wm_framebuffer_depth
    uniforms:
      0: wm_electrum_mat4
      1: wm_electrum_gl_texture