/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cloud_birb_wgpu_rust_Wgpu */

#ifndef _Included_cloud_birb_wgpu_rust_Wgpu
#define _Included_cloud_birb_wgpu_rust_Wgpu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cloud_birb_wgpu_rust_Wgpu
 * Method:    initializeWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cloud_birb_wgpu_rust_Wgpu_initializeWindow
  (JNIEnv *, jclass);

/*
 * Class:     cloud_birb_wgpu_rust_Wgpu
 * Method:    updateWindowTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cloud_birb_wgpu_rust_Wgpu_updateWindowTitle
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
